# Generated by Django 4.0.4 on 2022-05-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPP', '0009_fotos_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='webiste_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
