# Generated by Django 4.0.4 on 2022-05-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogAPP', '0010_profile_webiste_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='website_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
